#cloud-config
write_files:
  - path: /root/.ssh/ansible_test
    content: ${private_key}
    permissions: '0600'
  - path: /root/secrets.yml
    content: |
      rabbitmq:
        password: ${admin_password}
        cookie: ${secret_cookie}
      access_key: ${access_key}
      secret: ${secret}
  - path: /root/run_playbook.sh
    permissions: '0700'
    content: |
      #!/usr/bin/bash
      ansible-pull --private-key /root/.ssh/ansible_test --accept-host-key -e @/root/secrets.yml -U git@github.com:Patagona/backend-infrastructure.git -C ansible_test rabbitmq/ansible/playbook.yml


runcmd:
  - yum update -y
  - yum install python3 git -y
  - pip3 install ansible
  - echo "export PATH=$PATH:/usr/local/bin" >> /etc/profile
  - export PATH=$PATH:/usr/local/bin
  - ansible-galaxy collection install community.docker
  - /root/run_playbook.sh