#cloud-config
write_files:
  - path: /root/conf/enabled_plugins
    content: |
        [rabbitmq_management, rabbitmq_peer_discovery_aws].
  - path: /root/conf/rabbitmq.conf
    content: |
          cluster_formation.peer_discovery_backend = aws
          cluster_formation.aws.region = eu-west-1
          cluster_formation.aws.access_key_id = ${access_key}
          cluster_formation.aws.secret_key = ${secret}
          cluster_formation.aws.use_autoscaling_group = true
  
  - path: /root/remove_old_nodes.sh
    content: |
        #!/usr/bin/env bash
        nodes=($(egrep -o '[a-z0-9@-]+' <<< $(docker exec rabbitmq rabbitmqctl cluster_status --formatter json | jq .disk_nodes)))
        running_nodes=($(egrep -o '[a-z0-9@-]+' <<< $(docker exec rabbitmq rabbitmqctl cluster_status --formatter json | jq .running_nodes)))

        for node in $${nodes[@]}
        do
          match_count=0
          for rnode in $${running_nodes[@]}
          do
            if [ "$${node}" == "$${rnode}" ]
            then
                match_count=1
                break
            fi
          done
          if [ $match_count == 1 ]
            then
                continue
            else
              docker exec rabbitmq rabbitmqctl forget_cluster_node $node
            fi
        done
  
  - path: /root/configure.sh
    content: |
        #!/usr/bin/env bash
    
        docker exec rabbitmq rabbitmqctl add_user admin ${admin_password}
        docker exec rabbitmq rabbitmqctl set_user_tags admin administrator
        docker exec rabbitmq rabbitmqctl add_user rabbit ${rabbit_password}
        docker exec rabbitmq rabbitmqctl add_vhost /
        docker exec rabbitmq rabbitmqctl set_policy -p / ha-three "^" '{"ha-mode":"exactly", "ha-params":${sync_node_count}, "ha-sync-mode":"automatic", "message-ttl":${message_timeout}, "expires":${message_timeout}}'
        docker exec rabbitmq rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
        docker exec rabbitmq rabbitmqctl set_permissions -p / rabbit ".*" ".*" ".*"
        docker exec rabbitmq rabbitmqctl delete_user guest

  - path: /root/rebalance_quorum_queues.sh
    content: |
        #!/usr/bin/env bash
        
        docker exec rabbitmq rabbitmq-queues grow rabbit@$(echo $HOSTNAME | cut -d. -f1) all
        
  
  - path: /root/data/.erlang.cookie
    content: ${secret_cookie}
runcmd:
  - yum update -y
  - amazon-linux-extras install docker
  - yum install -y docker jq
  - systemctl enable docker
  - service docker start
  - chkconfig docker on
  - usermod -a -G docker ec2-user
  - chmod 600 /root/data/.erlang.cookie
  - docker volume create --opt type=none --opt o=bind --opt device=/root/data --driver=local   erlang_cookie
  - docker run -d --name rabbitmq --hostname $HOSTNAME -p 4369:4369 -p 5672:5672 -p 15672:15672 -p 25672:25672 -v erlang_cookie:/var/lib/rabbitmq -v /root/conf/:/etc/rabbitmq -v /root/bin:/tmp/bin rabbitmq:${rabbitmq_version}
  - sleep 60
  - bash /root/configure.sh
  - bash /root/remove_old_nodes.sh
  - bash /root/rebalance_quorum_queues.sh
